"""added user table

Revision ID: 4e7fc3e263b4
Revises: 83f6248107e9
Create Date: 2026-01-19 14:05:31.917845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7fc3e263b4'
down_revision: Union[str, Sequence[str], None] = '83f6248107e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caterers', sa.Column('country_name', sa.String(length=100), nullable=True))
    op.add_column('caterers', sa.Column('state_name', sa.String(length=100), nullable=True))
    op.add_column('caterers', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('caterers', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('caterers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('caterers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('caterers', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('caterers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('caterers', sa.Column('photo_folder_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('caterers', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('caterers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('caterers', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('caterers', 'gallery_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caterers', sa.Column('gallery_images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('caterers', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('caterers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('caterers', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('caterers', 'photo_folder_name')
    op.drop_column('caterers', 'rating')
    op.drop_column('caterers', 'rating_count')
    op.drop_column('caterers', 'longitude')
    op.drop_column('caterers', 'latitude')
    op.drop_column('caterers', 'website')
    op.drop_column('caterers', 'address')
    op.drop_column('caterers', 'state_name')
    op.drop_column('caterers', 'country_name')
    # ### end Alembic commands ###
