"""add main_image to caterers

Revision ID: 84b174f09b4d
Revises: edbb6eba1297
Create Date: 2026-02-06 16:14:07.512168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b174f09b4d'
down_revision: Union[str, Sequence[str], None] = 'edbb6eba1297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caterers', sa.Column('main_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caterers', 'main_image')
    # ### end Alembic commands ###
