"""add column for expirence

Revision ID: b6c4b1730bfe
Revises: 265325687c1c
Create Date: 2026-02-10 13:29:28.205441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c4b1730bfe'
down_revision: Union[str, Sequence[str], None] = '265325687c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caterers', 'country_name')
    op.drop_column('caterers', 'state_name')
    op.drop_column('caterers', 'address')
    op.drop_column('caterers', 'services_offered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caterers', sa.Column('services_offered', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('caterers', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('caterers', sa.Column('state_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('caterers', sa.Column('country_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
